language: java

jdk:
- oraclejdk8

deploy:
  provider: openshift
  edge:
    branch: openshift-deps
  user: omnifacesha@hotmail.com
  password:
    secure: iI9meOn6kfUvHrc3KDF9LH5Rl7Qy58y0lF+cSgkkPklNLnSlewYXx0pKqXeDLnm/peXNlQsIr4vcsceoPe17hlr1VYl935zh5SKCYQS69zUKTjW0Ct216+J9N3L90mm9vWmp2m8xe4J6lkDBhztfHdtaE9wglPWD9uDckevIgr7yfscqJ9Xu1fC1EG2aUoxWbH7Mg8ttfuuRIJMclxa3B3+spKBabJ3VHQy5Jjorl8m9b7bKOyK1o3PUHxYLRjkmF6fU9BSMnb5rBZ+2FW4MffLn0MAVmXlZyrk/LnFqU+KNvdNfZrKrEQVAIKPvXCCF/5Ugt7u1ANSmaEwahNSfegziM6NILU38k8bZRiTX7cNluiEkxlZRlkcHptqVBoTqDCpMILudF0EyVVy/6roORVrSNf0AFwC7ZyPTedlxmtbeB1x6vn9FifkP7YbQCAKb0fYO8S8h2tct7SAbHOO0c6k9um0UinQ8k2scVqHoFRLa1SfVl2r2aowV7nKNvP6npwwre2DnG/3jHL10V+JmaZo8YzdthJqo5sW3ka++ktIxcRn/AKWC0/8mrs4bVzrNPYnRQHURCNYWcUI0ggdkBpGPyidT9VDpLrh4m7R9JnF4nnGHq1c6M7oaU/J9wuzcVwEN38+SI3olpeBdAl5q73KvewGBXCVA2YAjLsgGuSs=
  app: javaeekickoff
  domain: omnifacessnapha
  on:
    repo: javaeekickoff/java-ee-kickoff-app
    branch: master
  skip_cleanup: true
